version: '3.8'

services:
  myapp:
    image: myapp-image
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${HOST_HTTP_PORT}:${CONTAINER_HTTP_PORT}" # Map host port 5129 to container port 80 (HTTP)
      - "${HOST_HTTPS_PORT}:${CONTAINER_HTTPS_PORT}" # Map host port 7044 to container port 443 (HTTPS)
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    env_file:
      - ".env" # Load .env file for general environment variables like API keys, host/container port numbers, etc.
    volumes:
      - .:/src # Optional: Mount the project directory in the container for development
