name: ASP.NET Core CI/CD Workflow

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '8.0'

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore -c Release

    - name: Create .env file
      run: |
        echo "FLICKR_API_KEY=${{ secrets.FLICKR_API_KEY }}" >> .env
        echo "FLICKR_API_SECRET=${{ secrets.FLICKR_API_SECRET }}" >> .env

    - name: Run Tests
      run: dotnet test --no-build -c Release --verbosity normal
      env:
        FLICKR_API_KEY: ${{ secrets.FLICKR_API_KEY }}
        FLICKR_API_SECRET: ${{ secrets.FLICKR_API_SECRET }}

    - name: Publish
      run: dotnet publish -c Release

    # Deployment step to Azure Web Apps
