name: ASP.NET Core CI/CD Workflow

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore

    - name: Create .env file
      run: |
        echo "FLICKR_API_KEY=${{ secrets.FLICKR_API_KEY }}" >> .env
        echo "FLICKR_API_SECRET=${{ secrets.FLICKR_API_SECRET }}" >> .env

    - name: Run tests
      run: dotnet test
      env:
        FLICKR_API_KEY: ${{ secrets.FLICKR_API_KEY }}
        FLICKR_API_SECRET: ${{ secrets.FLICKR_API_SECRET }}


